CREATE TABLE IF NOT EXISTS PASSWORD_RECOVERY_TOKEN (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  UUID_TOKEN VARCHAR(36) NOT NULL,
  USUARIO_ID BIGINT NOT NULL,
  TOKEN_HASH VARCHAR(64) NOT NULL,
  FECHA_EXPIRACION DATETIME NOT NULL,
  FECHA_USO DATETIME NULL,
  FECHA_CREACION DATETIME NOT NULL,
  IP_SOLICITUD VARCHAR(45) NULL,
  USER_AGENT VARCHAR(500) NULL,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_PASSWORD_RECOVERY_TOKEN PRIMARY KEY (ID),
  CONSTRAINT UK_PASSWORD_RECOVERY_UUID UNIQUE (UUID_TOKEN),
  CONSTRAINT UK_PASSWORD_RECOVERY_HASH UNIQUE (TOKEN_HASH),
  CONSTRAINT FK_PASSWORD_RECOVERY_USER FOREIGN KEY (USUARIO_ID) REFERENCES USUARIO_IDENTIDAD(ID),
  INDEX IDX_PASSWORD_RECOVERY_USER_ACTIVE (USUARIO_ID, FECHA_USO, FECHA_EXPIRACION)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO PARAMETRO_SEGURIDAD (CODIGO, NOMBRE, VALOR_TEXTO, TIPO_DATO, DESCRIPCION, ESTADO, FECHA_CREACION, FECHA_ACTUALIZACION, VERSION)
VALUES ('PASSWORD_RESET_TOKEN_MINUTES', 'Vigencia token recuperación', '15', 'INTEGER', 'Minutos de vigencia del token de recuperación de contraseña', 'ACTIVO', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP, 0)
ON DUPLICATE KEY UPDATE
  NOMBRE = VALUES(NOMBRE),
  VALOR_TEXTO = VALUES(VALOR_TEXTO),
  TIPO_DATO = VALUES(TIPO_DATO),
  DESCRIPCION = VALUES(DESCRIPCION);
