CREATE TABLE IF NOT EXISTS INTERNAL_USER_ONBOARDING (
  ID BIGINT NOT NULL AUTO_INCREMENT,
  IDEMPOTENCY_KEY VARCHAR(80) NOT NULL,
  PAYLOAD_HASH VARCHAR(64) NOT NULL,
  ESTADO VARCHAR(20) NOT NULL,
  UUID_IDENTIDAD VARCHAR(36) NULL,
  UUID_USUARIO_CORE VARCHAR(36) NULL,
  RESPUESTA_JSON JSON NULL,
  ERROR_ULTIMO VARCHAR(1000) NULL,
  FECHA_CREACION DATETIME NOT NULL,
  FECHA_ACTUALIZACION DATETIME NOT NULL,
  VERSION INT NOT NULL DEFAULT 0,
  CONSTRAINT PK_INTERNAL_USER_ONBOARDING PRIMARY KEY (ID),
  CONSTRAINT UK_INTERNAL_USER_ONBOARDING_KEY UNIQUE (IDEMPOTENCY_KEY),
  CONSTRAINT CK_INTERNAL_USER_ONBOARDING_STATUS CHECK (ESTADO IN ('EN_PROCESO','COMPLETADA','FALLIDA')),
  INDEX IDX_INTERNAL_USER_ONBOARDING_IDENTITY (UUID_IDENTIDAD)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
